package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientAllPropertiesEquals(Client expected, Client actual) {
        assertClientAutoGeneratedPropertiesEquals(expected, actual);
        assertClientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientAllUpdatablePropertiesEquals(Client expected, Client actual) {
        assertClientUpdatableFieldsEquals(expected, actual);
        assertClientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientAutoGeneratedPropertiesEquals(Client expected, Client actual) {
        assertThat(actual)
            .as("Verify Client auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientUpdatableFieldsEquals(Client expected, Client actual) {
        assertThat(actual)
            .as("Verify Client relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNomComplet()).as("check nomComplet").isEqualTo(expected.getNomComplet()))
            .satisfies(a -> assertThat(a.getPhotoUrl()).as("check photoUrl").isEqualTo(expected.getPhotoUrl()))
            .satisfies(a -> assertThat(a.getDateNaissance()).as("check dateNaissance").isEqualTo(expected.getDateNaissance()))
            .satisfies(a -> assertThat(a.getLieuNaissance()).as("check lieuNaissance").isEqualTo(expected.getLieuNaissance()))
            .satisfies(a -> assertThat(a.getNationalite()).as("check nationalite").isEqualTo(expected.getNationalite()))
            .satisfies(a -> assertThat(a.getGenre()).as("check genre").isEqualTo(expected.getGenre()))
            .satisfies(a -> assertThat(a.getFonction()).as("check fonction").isEqualTo(expected.getFonction()))
            .satisfies(a -> assertThat(a.getLanguePreferee()).as("check languePreferee").isEqualTo(expected.getLanguePreferee()))
            .satisfies(a -> assertThat(a.getTelephonePrincipal()).as("check telephonePrincipal").isEqualTo(expected.getTelephonePrincipal())
            )
            .satisfies(a -> assertThat(a.getWhatsapp()).as("check whatsapp").isEqualTo(expected.getWhatsapp()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getAdressePersonnelle()).as("check adressePersonnelle").isEqualTo(expected.getAdressePersonnelle())
            )
            .satisfies(a -> assertThat(a.getAdressesLivraison()).as("check adressesLivraison").isEqualTo(expected.getAdressesLivraison()))
            .satisfies(a -> assertThat(a.getReseauxSociaux()).as("check reseauxSociaux").isEqualTo(expected.getReseauxSociaux()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientUpdatableRelationshipsEquals(Client expected, Client actual) {
        assertThat(actual)
            .as("Verify Client relationships")
            .satisfies(a -> assertThat(a.getPays()).as("check pays").isEqualTo(expected.getPays()))
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
