package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContactAssocieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactAssocieAllPropertiesEquals(ContactAssocie expected, ContactAssocie actual) {
        assertContactAssocieAutoGeneratedPropertiesEquals(expected, actual);
        assertContactAssocieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactAssocieAllUpdatablePropertiesEquals(ContactAssocie expected, ContactAssocie actual) {
        assertContactAssocieUpdatableFieldsEquals(expected, actual);
        assertContactAssocieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactAssocieAutoGeneratedPropertiesEquals(ContactAssocie expected, ContactAssocie actual) {
        assertThat(actual)
            .as("Verify ContactAssocie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactAssocieUpdatableFieldsEquals(ContactAssocie expected, ContactAssocie actual) {
        assertThat(actual)
            .as("Verify ContactAssocie relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getPrenom()).as("check prenom").isEqualTo(expected.getPrenom()))
            .satisfies(a -> assertThat(a.getRelation()).as("check relation").isEqualTo(expected.getRelation()))
            .satisfies(a -> assertThat(a.getTelephone()).as("check telephone").isEqualTo(expected.getTelephone()))
            .satisfies(a -> assertThat(a.getWhatsapp()).as("check whatsapp").isEqualTo(expected.getWhatsapp()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getAutorisation()).as("check autorisation").isEqualTo(expected.getAutorisation()))
            .satisfies(a -> assertThat(a.getRemarques()).as("check remarques").isEqualTo(expected.getRemarques()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactAssocieUpdatableRelationshipsEquals(ContactAssocie expected, ContactAssocie actual) {
        assertThat(actual)
            .as("Verify ContactAssocie relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
