package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CycleActivationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleActivationAllPropertiesEquals(CycleActivation expected, CycleActivation actual) {
        assertCycleActivationAutoGeneratedPropertiesEquals(expected, actual);
        assertCycleActivationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleActivationAllUpdatablePropertiesEquals(CycleActivation expected, CycleActivation actual) {
        assertCycleActivationUpdatableFieldsEquals(expected, actual);
        assertCycleActivationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleActivationAutoGeneratedPropertiesEquals(CycleActivation expected, CycleActivation actual) {
        assertThat(actual)
            .as("Verify CycleActivation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleActivationUpdatableFieldsEquals(CycleActivation expected, CycleActivation actual) {
        assertThat(actual)
            .as("Verify CycleActivation relevant properties")
            .satisfies(a -> assertThat(a.getNumeroCycle()).as("check numeroCycle").isEqualTo(expected.getNumeroCycle()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getStatutCycle()).as("check statutCycle").isEqualTo(expected.getStatutCycle()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleActivationUpdatableRelationshipsEquals(CycleActivation expected, CycleActivation actual) {
        assertThat(actual)
            .as("Verify CycleActivation relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
