package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DemandeClientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeClientAllPropertiesEquals(DemandeClient expected, DemandeClient actual) {
        assertDemandeClientAutoGeneratedPropertiesEquals(expected, actual);
        assertDemandeClientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeClientAllUpdatablePropertiesEquals(DemandeClient expected, DemandeClient actual) {
        assertDemandeClientUpdatableFieldsEquals(expected, actual);
        assertDemandeClientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeClientAutoGeneratedPropertiesEquals(DemandeClient expected, DemandeClient actual) {
        assertThat(actual)
            .as("Verify DemandeClient auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeClientUpdatableFieldsEquals(DemandeClient expected, DemandeClient actual) {
        assertThat(actual)
            .as("Verify DemandeClient relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getDateDemande()).as("check dateDemande").isEqualTo(expected.getDateDemande()))
            .satisfies(a -> assertThat(a.getServicePrincipal()).as("check servicePrincipal").isEqualTo(expected.getServicePrincipal()))
            .satisfies(a -> assertThat(a.getProvenance()).as("check provenance").isEqualTo(expected.getProvenance()))
            .satisfies(a -> assertThat(a.getNombreProduits()).as("check nombreProduits").isEqualTo(expected.getNombreProduits()))
            .satisfies(a -> assertThat(a.getRemarqueGenerale()).as("check remarqueGenerale").isEqualTo(expected.getRemarqueGenerale()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeClientUpdatableRelationshipsEquals(DemandeClient expected, DemandeClient actual) {
        assertThat(actual)
            .as("Verify DemandeClient relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()))
            .satisfies(a -> assertThat(a.getDevise()).as("check devise").isEqualTo(expected.getDevise()))
            .satisfies(a -> assertThat(a.getIncoterm()).as("check incoterm").isEqualTo(expected.getIncoterm()))
            .satisfies(a -> assertThat(a.getSousServices()).as("check sousServices").isEqualTo(expected.getSousServices()));
    }
}
