package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeviseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviseAllPropertiesEquals(Devise expected, Devise actual) {
        assertDeviseAutoGeneratedPropertiesEquals(expected, actual);
        assertDeviseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviseAllUpdatablePropertiesEquals(Devise expected, Devise actual) {
        assertDeviseUpdatableFieldsEquals(expected, actual);
        assertDeviseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviseAutoGeneratedPropertiesEquals(Devise expected, Devise actual) {
        assertThat(actual)
            .as("Verify Devise auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviseUpdatableFieldsEquals(Devise expected, Devise actual) {
        assertThat(actual)
            .as("Verify Devise relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNomComplet()).as("check nomComplet").isEqualTo(expected.getNomComplet()))
            .satisfies(a -> assertThat(a.getSymbole()).as("check symbole").isEqualTo(expected.getSymbole()))
            .satisfies(a -> assertThat(a.getPays()).as("check pays").isEqualTo(expected.getPays()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviseUpdatableRelationshipsEquals(Devise expected, Devise actual) {
        // empty method
    }
}
