package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentClientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentClientAllPropertiesEquals(DocumentClient expected, DocumentClient actual) {
        assertDocumentClientAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentClientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentClientAllUpdatablePropertiesEquals(DocumentClient expected, DocumentClient actual) {
        assertDocumentClientUpdatableFieldsEquals(expected, actual);
        assertDocumentClientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentClientAutoGeneratedPropertiesEquals(DocumentClient expected, DocumentClient actual) {
        assertThat(actual)
            .as("Verify DocumentClient auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentClientUpdatableFieldsEquals(DocumentClient expected, DocumentClient actual) {
        assertThat(actual)
            .as("Verify DocumentClient relevant properties")
            .satisfies(a -> assertThat(a.getTypeDocument()).as("check typeDocument").isEqualTo(expected.getTypeDocument()))
            .satisfies(a -> assertThat(a.getNumeroDocument()).as("check numeroDocument").isEqualTo(expected.getNumeroDocument()))
            .satisfies(a -> assertThat(a.getFichierUrl()).as("check fichierUrl").isEqualTo(expected.getFichierUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentClientUpdatableRelationshipsEquals(DocumentClient expected, DocumentClient actual) {
        assertThat(actual)
            .as("Verify DocumentClient relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
