package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EtatInteractionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtatInteractionAllPropertiesEquals(EtatInteraction expected, EtatInteraction actual) {
        assertEtatInteractionAutoGeneratedPropertiesEquals(expected, actual);
        assertEtatInteractionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtatInteractionAllUpdatablePropertiesEquals(EtatInteraction expected, EtatInteraction actual) {
        assertEtatInteractionUpdatableFieldsEquals(expected, actual);
        assertEtatInteractionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtatInteractionAutoGeneratedPropertiesEquals(EtatInteraction expected, EtatInteraction actual) {
        assertThat(actual)
            .as("Verify EtatInteraction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtatInteractionUpdatableFieldsEquals(EtatInteraction expected, EtatInteraction actual) {
        assertThat(actual)
            .as("Verify EtatInteraction relevant properties")
            .satisfies(a -> assertThat(a.getEtat()).as("check etat").isEqualTo(expected.getEtat()))
            .satisfies(a -> assertThat(a.getDateEtat()).as("check dateEtat").isEqualTo(expected.getDateEtat()))
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()))
            .satisfies(a -> assertThat(a.getObservation()).as("check observation").isEqualTo(expected.getObservation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtatInteractionUpdatableRelationshipsEquals(EtatInteraction expected, EtatInteraction actual) {
        assertThat(actual)
            .as("Verify EtatInteraction relationships")
            .satisfies(a -> assertThat(a.getHistorique()).as("check historique").isEqualTo(expected.getHistorique()))
            .satisfies(a -> assertThat(a.getCycle()).as("check cycle").isEqualTo(expected.getCycle()));
    }
}
