package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoriqueCRMAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCRMAllPropertiesEquals(HistoriqueCRM expected, HistoriqueCRM actual) {
        assertHistoriqueCRMAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriqueCRMAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCRMAllUpdatablePropertiesEquals(HistoriqueCRM expected, HistoriqueCRM actual) {
        assertHistoriqueCRMUpdatableFieldsEquals(expected, actual);
        assertHistoriqueCRMUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCRMAutoGeneratedPropertiesEquals(HistoriqueCRM expected, HistoriqueCRM actual) {
        assertThat(actual)
            .as("Verify HistoriqueCRM auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCRMUpdatableFieldsEquals(HistoriqueCRM expected, HistoriqueCRM actual) {
        assertThat(actual)
            .as("Verify HistoriqueCRM relevant properties")
            .satisfies(a -> assertThat(a.getDateInteraction()).as("check dateInteraction").isEqualTo(expected.getDateInteraction()))
            .satisfies(a -> assertThat(a.getCanal()).as("check canal").isEqualTo(expected.getCanal()))
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()))
            .satisfies(a -> assertThat(a.getResume()).as("check resume").isEqualTo(expected.getResume()))
            .satisfies(a -> assertThat(a.getEtat()).as("check etat").isEqualTo(expected.getEtat()))
            .satisfies(a -> assertThat(a.getObservation()).as("check observation").isEqualTo(expected.getObservation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCRMUpdatableRelationshipsEquals(HistoriqueCRM expected, HistoriqueCRM actual) {
        assertThat(actual)
            .as("Verify HistoriqueCRM relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
