package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryAllPropertiesEquals(History expected, History actual) {
        assertHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryAllUpdatablePropertiesEquals(History expected, History actual) {
        assertHistoryUpdatableFieldsEquals(expected, actual);
        assertHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryAutoGeneratedPropertiesEquals(History expected, History actual) {
        assertThat(actual)
            .as("Verify History auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryUpdatableFieldsEquals(History expected, History actual) {
        assertThat(actual)
            .as("Verify History relevant properties")
            .satisfies(a -> assertThat(a.getEntityName()).as("check entityName").isEqualTo(expected.getEntityName()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getFieldChanged()).as("check fieldChanged").isEqualTo(expected.getFieldChanged()))
            .satisfies(a -> assertThat(a.getOldValue()).as("check oldValue").isEqualTo(expected.getOldValue()))
            .satisfies(a -> assertThat(a.getNewValue()).as("check newValue").isEqualTo(expected.getNewValue()))
            .satisfies(a -> assertThat(a.getPerformedBy()).as("check performedBy").isEqualTo(expected.getPerformedBy()))
            .satisfies(a -> assertThat(a.getPerformedDate()).as("check performedDate").isEqualTo(expected.getPerformedDate()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryUpdatableRelationshipsEquals(History expected, History actual) {
        // empty method
    }
}
