package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IncotermAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncotermAllPropertiesEquals(Incoterm expected, Incoterm actual) {
        assertIncotermAutoGeneratedPropertiesEquals(expected, actual);
        assertIncotermAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncotermAllUpdatablePropertiesEquals(Incoterm expected, Incoterm actual) {
        assertIncotermUpdatableFieldsEquals(expected, actual);
        assertIncotermUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncotermAutoGeneratedPropertiesEquals(Incoterm expected, Incoterm actual) {
        assertThat(actual)
            .as("Verify Incoterm auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncotermUpdatableFieldsEquals(Incoterm expected, Incoterm actual) {
        assertThat(actual)
            .as("Verify Incoterm relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncotermUpdatableRelationshipsEquals(Incoterm expected, Incoterm actual) {
        // empty method
    }
}
