package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InternalUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalUserAllPropertiesEquals(InternalUser expected, InternalUser actual) {
        assertInternalUserAutoGeneratedPropertiesEquals(expected, actual);
        assertInternalUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalUserAllUpdatablePropertiesEquals(InternalUser expected, InternalUser actual) {
        assertInternalUserUpdatableFieldsEquals(expected, actual);
        assertInternalUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalUserAutoGeneratedPropertiesEquals(InternalUser expected, InternalUser actual) {
        assertThat(actual)
            .as("Verify InternalUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalUserUpdatableFieldsEquals(InternalUser expected, InternalUser actual) {
        assertThat(actual)
            .as("Verify InternalUser relevant properties")
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalUserUpdatableRelationshipsEquals(InternalUser expected, InternalUser actual) {
        // empty method
    }
}
