package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KycClientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycClientAllPropertiesEquals(KycClient expected, KycClient actual) {
        assertKycClientAutoGeneratedPropertiesEquals(expected, actual);
        assertKycClientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycClientAllUpdatablePropertiesEquals(KycClient expected, KycClient actual) {
        assertKycClientUpdatableFieldsEquals(expected, actual);
        assertKycClientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycClientAutoGeneratedPropertiesEquals(KycClient expected, KycClient actual) {
        assertThat(actual)
            .as("Verify KycClient auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycClientUpdatableFieldsEquals(KycClient expected, KycClient actual) {
        assertThat(actual)
            .as("Verify KycClient relevant properties")
            .satisfies(a -> assertThat(a.getScoreStaff()).as("check scoreStaff").isEqualTo(expected.getScoreStaff()))
            .satisfies(a -> assertThat(a.getComportements()).as("check comportements").isEqualTo(expected.getComportements()))
            .satisfies(a -> assertThat(a.getRemarques()).as("check remarques").isEqualTo(expected.getRemarques()))
            .satisfies(a -> assertThat(a.getCompletudeKyc()).as("check completudeKyc").isEqualTo(expected.getCompletudeKyc()))
            .satisfies(a -> assertThat(a.getResponsable()).as("check responsable").isEqualTo(expected.getResponsable()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycClientUpdatableRelationshipsEquals(KycClient expected, KycClient actual) {
        assertThat(actual)
            .as("Verify KycClient relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
