package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LangueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLangueAllPropertiesEquals(Langue expected, Langue actual) {
        assertLangueAutoGeneratedPropertiesEquals(expected, actual);
        assertLangueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLangueAllUpdatablePropertiesEquals(Langue expected, Langue actual) {
        assertLangueUpdatableFieldsEquals(expected, actual);
        assertLangueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLangueAutoGeneratedPropertiesEquals(Langue expected, Langue actual) {
        assertThat(actual)
            .as("Verify Langue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLangueUpdatableFieldsEquals(Langue expected, Langue actual) {
        assertThat(actual)
            .as("Verify Langue relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLangueUpdatableRelationshipsEquals(Langue expected, Langue actual) {
        // empty method
    }
}
