package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaysAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaysAllPropertiesEquals(Pays expected, Pays actual) {
        assertPaysAutoGeneratedPropertiesEquals(expected, actual);
        assertPaysAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaysAllUpdatablePropertiesEquals(Pays expected, Pays actual) {
        assertPaysUpdatableFieldsEquals(expected, actual);
        assertPaysUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaysAutoGeneratedPropertiesEquals(Pays expected, Pays actual) {
        assertThat(actual)
            .as("Verify Pays auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaysUpdatableFieldsEquals(Pays expected, Pays actual) {
        assertThat(actual)
            .as("Verify Pays relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getIndicatif()).as("check indicatif").isEqualTo(expected.getIndicatif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaysUpdatableRelationshipsEquals(Pays expected, Pays actual) {
        // empty method
    }
}
