package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProduitDemandeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitDemandeAllPropertiesEquals(ProduitDemande expected, ProduitDemande actual) {
        assertProduitDemandeAutoGeneratedPropertiesEquals(expected, actual);
        assertProduitDemandeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitDemandeAllUpdatablePropertiesEquals(ProduitDemande expected, ProduitDemande actual) {
        assertProduitDemandeUpdatableFieldsEquals(expected, actual);
        assertProduitDemandeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitDemandeAutoGeneratedPropertiesEquals(ProduitDemande expected, ProduitDemande actual) {
        assertThat(actual)
            .as("Verify ProduitDemande auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitDemandeUpdatableFieldsEquals(ProduitDemande expected, ProduitDemande actual) {
        assertThat(actual)
            .as("Verify ProduitDemande relevant properties")
            .satisfies(a -> assertThat(a.getTypeProduit()).as("check typeProduit").isEqualTo(expected.getTypeProduit()))
            .satisfies(a -> assertThat(a.getTypeDemande()).as("check typeDemande").isEqualTo(expected.getTypeDemande()))
            .satisfies(a -> assertThat(a.getNomProduit()).as("check nomProduit").isEqualTo(expected.getNomProduit()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getQuantite()).as("check quantite").isEqualTo(expected.getQuantite()))
            .satisfies(a -> assertThat(a.getUnite()).as("check unite").isEqualTo(expected.getUnite()))
            .satisfies(a -> assertThat(a.getPrix()).as("check prix").isEqualTo(expected.getPrix()))
            .satisfies(a -> assertThat(a.getFraisExpedition()).as("check fraisExpedition").isEqualTo(expected.getFraisExpedition()))
            .satisfies(a -> assertThat(a.getPoidsKg()).as("check poidsKg").isEqualTo(expected.getPoidsKg()))
            .satisfies(a -> assertThat(a.getVolumeTotalCbm()).as("check volumeTotalCbm").isEqualTo(expected.getVolumeTotalCbm()))
            .satisfies(a -> assertThat(a.getDimensions()).as("check dimensions").isEqualTo(expected.getDimensions()))
            .satisfies(a -> assertThat(a.getNombreCartons()).as("check nombreCartons").isEqualTo(expected.getNombreCartons()))
            .satisfies(a -> assertThat(a.getPiecesParCarton()).as("check piecesParCarton").isEqualTo(expected.getPiecesParCarton()))
            .satisfies(a -> assertThat(a.getHsCode()).as("check hsCode").isEqualTo(expected.getHsCode()))
            .satisfies(a -> assertThat(a.getPrixCible()).as("check prixCible").isEqualTo(expected.getPrixCible()))
            .satisfies(a -> assertThat(a.getOrigine()).as("check origine").isEqualTo(expected.getOrigine()))
            .satisfies(a -> assertThat(a.getContactFournisseur()).as("check contactFournisseur").isEqualTo(expected.getContactFournisseur())
            )
            .satisfies(a -> assertThat(a.getAdresseChargement()).as("check adresseChargement").isEqualTo(expected.getAdresseChargement()))
            .satisfies(a ->
                assertThat(a.getAdresseDechargement()).as("check adresseDechargement").isEqualTo(expected.getAdresseDechargement())
            )
            .satisfies(a -> assertThat(a.getFicheTechniqueUrl()).as("check ficheTechniqueUrl").isEqualTo(expected.getFicheTechniqueUrl()))
            .satisfies(a -> assertThat(a.getPhotosUrl()).as("check photosUrl").isEqualTo(expected.getPhotosUrl()))
            .satisfies(a -> assertThat(a.getPiecesJointesUrl()).as("check piecesJointesUrl").isEqualTo(expected.getPiecesJointesUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitDemandeUpdatableRelationshipsEquals(ProduitDemande expected, ProduitDemande actual) {
        assertThat(actual)
            .as("Verify ProduitDemande relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()));
    }
}
