package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProspectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectAllPropertiesEquals(Prospect expected, Prospect actual) {
        assertProspectAutoGeneratedPropertiesEquals(expected, actual);
        assertProspectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectAllUpdatablePropertiesEquals(Prospect expected, Prospect actual) {
        assertProspectUpdatableFieldsEquals(expected, actual);
        assertProspectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectAutoGeneratedPropertiesEquals(Prospect expected, Prospect actual) {
        assertThat(actual)
            .as("Verify Prospect auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectUpdatableFieldsEquals(Prospect expected, Prospect actual) {
        assertThat(actual)
            .as("Verify Prospect relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectUpdatableRelationshipsEquals(Prospect expected, Prospect actual) {
        assertThat(actual)
            .as("Verify Prospect relationships")
            .satisfies(a -> assertThat(a.getConvertedTo()).as("check convertedTo").isEqualTo(expected.getConvertedTo()))
            .satisfies(a -> assertThat(a.getConvertedBy()).as("check convertedBy").isEqualTo(expected.getConvertedBy()));
    }
}
