package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProspectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectAllPropertiesEquals(Prospect expected, Prospect actual) {
        assertProspectAutoGeneratedPropertiesEquals(expected, actual);
        assertProspectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectAllUpdatablePropertiesEquals(Prospect expected, Prospect actual) {
        assertProspectUpdatableFieldsEquals(expected, actual);
        assertProspectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectAutoGeneratedPropertiesEquals(Prospect expected, Prospect actual) {
        assertThat(actual)
            .as("Verify Prospect auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectUpdatableFieldsEquals(Prospect expected, Prospect actual) {
        assertThat(actual)
            .as("Verify Prospect relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhone1()).as("check phone1").isEqualTo(expected.getPhone1()))
            .satisfies(a -> assertThat(a.getPhone2()).as("check phone2").isEqualTo(expected.getPhone2()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getCin()).as("check cin").isEqualTo(expected.getCin()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getDeliveryAddress()).as("check deliveryAddress").isEqualTo(expected.getDeliveryAddress()))
            .satisfies(a -> assertThat(a.getReferredBy()).as("check referredBy").isEqualTo(expected.getReferredBy()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getConvertedDate()).as("check convertedDate").isEqualTo(expected.getConvertedDate()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectUpdatableRelationshipsEquals(Prospect expected, Prospect actual) {
        assertThat(actual)
            .as("Verify Prospect relationships")
            .satisfies(a -> assertThat(a.getConvertedTo()).as("check convertedTo").isEqualTo(expected.getConvertedTo()))
            .satisfies(a -> assertThat(a.getConvertedBy()).as("check convertedBy").isEqualTo(expected.getConvertedBy()))
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
