package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RappelAgentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRappelAgentAllPropertiesEquals(RappelAgent expected, RappelAgent actual) {
        assertRappelAgentAutoGeneratedPropertiesEquals(expected, actual);
        assertRappelAgentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRappelAgentAllUpdatablePropertiesEquals(RappelAgent expected, RappelAgent actual) {
        assertRappelAgentUpdatableFieldsEquals(expected, actual);
        assertRappelAgentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRappelAgentAutoGeneratedPropertiesEquals(RappelAgent expected, RappelAgent actual) {
        assertThat(actual)
            .as("Verify RappelAgent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRappelAgentUpdatableFieldsEquals(RappelAgent expected, RappelAgent actual) {
        assertThat(actual)
            .as("Verify RappelAgent relevant properties")
            .satisfies(a -> assertThat(a.getRappelDate()).as("check rappelDate").isEqualTo(expected.getRappelDate()))
            .satisfies(a -> assertThat(a.getRappelMessage()).as("check rappelMessage").isEqualTo(expected.getRappelMessage()))
            .satisfies(a -> assertThat(a.getStatutRappel()).as("check statutRappel").isEqualTo(expected.getStatutRappel()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRappelAgentUpdatableRelationshipsEquals(RappelAgent expected, RappelAgent actual) {
        assertThat(actual)
            .as("Verify RappelAgent relationships")
            .satisfies(a -> assertThat(a.getEtat()).as("check etat").isEqualTo(expected.getEtat()))
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()))
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()));
    }
}
