package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReseauSocialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReseauSocialAllPropertiesEquals(ReseauSocial expected, ReseauSocial actual) {
        assertReseauSocialAutoGeneratedPropertiesEquals(expected, actual);
        assertReseauSocialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReseauSocialAllUpdatablePropertiesEquals(ReseauSocial expected, ReseauSocial actual) {
        assertReseauSocialUpdatableFieldsEquals(expected, actual);
        assertReseauSocialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReseauSocialAutoGeneratedPropertiesEquals(ReseauSocial expected, ReseauSocial actual) {
        assertThat(actual)
            .as("Verify ReseauSocial auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReseauSocialUpdatableFieldsEquals(ReseauSocial expected, ReseauSocial actual) {
        assertThat(actual)
            .as("Verify ReseauSocial relevant properties")
            .satisfies(a -> assertThat(a.getPlateforme()).as("check plateforme").isEqualTo(expected.getPlateforme()))
            .satisfies(a -> assertThat(a.getUrlProfil()).as("check urlProfil").isEqualTo(expected.getUrlProfil()))
            .satisfies(a -> assertThat(a.getUsername()).as("check username").isEqualTo(expected.getUsername()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReseauSocialUpdatableRelationshipsEquals(ReseauSocial expected, ReseauSocial actual) {
        assertThat(actual)
            .as("Verify ReseauSocial relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
