package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SocieteLieeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteLieeAllPropertiesEquals(SocieteLiee expected, SocieteLiee actual) {
        assertSocieteLieeAutoGeneratedPropertiesEquals(expected, actual);
        assertSocieteLieeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteLieeAllUpdatablePropertiesEquals(SocieteLiee expected, SocieteLiee actual) {
        assertSocieteLieeUpdatableFieldsEquals(expected, actual);
        assertSocieteLieeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteLieeAutoGeneratedPropertiesEquals(SocieteLiee expected, SocieteLiee actual) {
        assertThat(actual)
            .as("Verify SocieteLiee auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteLieeUpdatableFieldsEquals(SocieteLiee expected, SocieteLiee actual) {
        assertThat(actual)
            .as("Verify SocieteLiee relevant properties")
            .satisfies(a -> assertThat(a.getRaisonSociale()).as("check raisonSociale").isEqualTo(expected.getRaisonSociale()))
            .satisfies(a -> assertThat(a.getFormeJuridique()).as("check formeJuridique").isEqualTo(expected.getFormeJuridique()))
            .satisfies(a -> assertThat(a.getIce()).as("check ice").isEqualTo(expected.getIce()))
            .satisfies(a -> assertThat(a.getRc()).as("check rc").isEqualTo(expected.getRc()))
            .satisfies(a -> assertThat(a.getNif()).as("check nif").isEqualTo(expected.getNif()))
            .satisfies(a -> assertThat(a.getSecteurActivite()).as("check secteurActivite").isEqualTo(expected.getSecteurActivite()))
            .satisfies(a -> assertThat(a.getTailleEntreprise()).as("check tailleEntreprise").isEqualTo(expected.getTailleEntreprise()))
            .satisfies(a -> assertThat(a.getAdresseSiege()).as("check adresseSiege").isEqualTo(expected.getAdresseSiege()))
            .satisfies(a -> assertThat(a.getRepresentantLegal()).as("check representantLegal").isEqualTo(expected.getRepresentantLegal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteLieeUpdatableRelationshipsEquals(SocieteLiee expected, SocieteLiee actual) {
        assertThat(actual)
            .as("Verify SocieteLiee relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
