package com.ultex.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SousServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousServiceAllPropertiesEquals(SousService expected, SousService actual) {
        assertSousServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertSousServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousServiceAllUpdatablePropertiesEquals(SousService expected, SousService actual) {
        assertSousServiceUpdatableFieldsEquals(expected, actual);
        assertSousServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousServiceAutoGeneratedPropertiesEquals(SousService expected, SousService actual) {
        assertThat(actual)
            .as("Verify SousService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousServiceUpdatableFieldsEquals(SousService expected, SousService actual) {
        assertThat(actual)
            .as("Verify SousService relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousServiceUpdatableRelationshipsEquals(SousService expected, SousService actual) {
        assertThat(actual)
            .as("Verify SousService relationships")
            .satisfies(a -> assertThat(a.getDemandes()).as("check demandes").isEqualTo(expected.getDemandes()));
    }
}
